name: weather_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  build_runner: ^2.4.8
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  lottie: ^3.1.0
  provider: ^6.1.2
  retrofit: ^4.1.0
  flutter_secure_storage: ^9.0.0
  retrofit_generator: ^8.1.0
  weather: ^3.1.1
  envied: ^0.5.3
  flutter_bloc: ^8.1.4
  intl: ^0.19.0
  audioplayers: ^5.2.1
  http: ^1.2.0

dev_dependencies:

  envied_generator: ^0.5.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets: 
    - assets/
